bulletin_boards/accounts/urls.py
# from django.urls import path

bulletin_boards/bulletin_boards/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import SignUp
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', ArticleList.as_view(), name='article'),
    path('article/<int:pk>/', ArticleDetail.as_view(), name='post'),
    path('article/articles_create/', ArticleCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit', ArticleUpdate.as_view(), name='articles_edit'),
    path('article/<int:pk>/delete', ArticleDelete.as_view(), name='article_delete'),
    path('comment/<int:pk>/delete', CommentDelete.as_view(), name='comment_delete'),
    path('comment/<int:pk>/add', comment_add, name='comment_add'),
    path('<int:pk>/comment/create/', CommentCreate.as_view(), name='add_comment'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('confirm/', ConfirmUser.as_view(), name='confirm_user'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletin_boards/bulletin_boards/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Article(models.Model):
    TYPE = (
        ('tank', 'Танки'),
        ('heal', 'Хилы'),
        ('dd', 'ДД'),
        ('buyers', 'Торговцы'),
        ('gildemaster', 'Гилдмастеры'),
        ('quest', 'Кестгиеры'),
        ('smith', 'Кузнецы'),
        ('tanner', 'Кожевники'),
        ('potion', 'Зельевары'),
        ('spellmaster', 'Мастера заклинаний'),
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=64)
    text = RichTextUploadingField()  # !
    category = models.CharField(max_length=20, choices=TYPE, default='tank')
    post_time = models.DateTimeField(auto_now_add=True)  # автоматически добавляемая дата и время создания;
    upload = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True, default=None, null=True, verbose_name='upload')

    # def __str__(self):
    #     return f'author - {self.author}: title - {self.title}; text - {self.text[:20]}; category - {self.category}; upload - {self.upload}'

    def __str__(self):
        return f'author - {self.author}: title - {self.title}'

    def get_absolute_url(self):
        return reverse('article', args=[str(self.id)])


class User(AbstractUser):
    code = models.CharField(max_length=15, blank=True, null=True)


class Comment(models.Model):
    comment_post = models.ForeignKey(Article, on_delete=models.CASCADE,
                                     verbose_name='Комментарии')  # связь с моделью Article;
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment',
                                     verbose_name='Автор')  # связь с моделью User
    text = models.TextField(verbose_name='Описание')  # текст комментария;
    comment_time = models.DateTimeField(auto_now_add=True,
                                        verbose_name='Время публикации')  # дата и время создания комментария;
    status = models.BooleanField(default=False, verbose_name='статус')

    def __str__(self):
        return f'{self.comment_user}: {self.text} {self.comment_post} {self.comment_time} {self.status}'

    def get_absolut_url(self):
        return reverse('article_detail', kwargs={'pk': self.comment_post_id})

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'
        ordering = ['id']

bulletin_boards/templates/article/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление публикации</h1>
<h1>{{object.title}} от {{object.post_time}}</h1>
<hr>
{% if request.user.id == object.author.id %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% else %}
<h1>Вы не автор поста! </h1>
{% endif %}
{% endblock content %}

bulletin_boards/templates/article/article_detail.html
{% extends 'flatpages/default.html' %}

<!--!!! УДАЛИТЬ это !!!-->


{% block title %}
{{ article.title }}
{% endblock title %}

{% load custom_filters %}
{% load custom_tags %}

{% block content %}
{% if post %}
<table width="100%" style="margin-top: 35px">
    <tr>
        <td><u>{% trans "Heading" %}</u></td>
        <td><u>{% trans "Date" %}</u></td>
        <td><u>{% trans "Content" %}</u></td>
        <td><u>{% trans "Rating" %}</u></td>
        <td><u>{% trans "Category" %}</u></td>
    </tr>
    <tr>
        <td>{{ article.title }}</td>
        <td>{{ article.post_time|date:'d M Y' }}</td>
        <td>{{ article.text|censor}}</td>     <!--|censor-->
        <td>{{ article.rating }}</td>
        {% for cat in post.category.all %}
        <td>{{ cat.category_name }}</td>
        {% endfor %}
    </tr>
</table>
{% else %}
<h3>{% trans "There are no publications!" %}"</h3>
{% endif %}

<form action="{% url 'comment_create' article_id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Создать отклик">
</form>

{% if article.comment_set.all %}
<h4>Все отклики:</h4>
{% for comment in article.comment_set.all %}
<p>{{ comment.comment_user.username }}</p>
<p>{{ comment.text }}</p>
{% endfor %}
{% endif %}
{% if perms.bulletin_boards.add_article %}
    <br><br><small><button href="{% url 'article_create %}">Добавить новое объявление</button></small>

{% endblock content %}

bulletin_boards/templates/article/articles_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать объявление</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

bulletin_boards/templates/article/comment_add.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Принять и опубликовать отклик</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="submit" value="Да!"/>
</form>
{% endblock content %}

bulletin_boards/templates/article/comment_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление отклика</h1>
<hr>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Удаляем "{{ object.comment }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}